// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define tes_Klasse1_BODY

/************************************************************
 Klasse1 class body
 ************************************************************/

// include associated header file
#include "tes/Klasse1.h"

// Derived includes directives

namespace tes {

// static attributes (if any)
/**
 * 
 */
int Klasse1::Counter;

/**
 * 
 * @return zahl 
 */
int Klasse1::getVariable2() {
}

/**
 * 
 */
void Klasse1::Methode2() {
}

/**
 * 
 */
void Klasse1::Methode3() {
}

/**
 * 
 * @param zahl 
 */
void Klasse1::setVariable2(int /*in*/zahl) {
}

/**
 * 
 * @param Value 
 */
Klasse1::Klasse1(int /*in*/Value) {
}

/**
 * 
 */
Klasse1::~Klasse1() {
}

/**
 * 
 */
void Klasse1::Mehtode4() {
}
/**
 *
 */
void Klasse1::printName(){
	std::cout<<Klasse2::getName()<<std::endl;
}
} // of namespace tes

/************************************************************
 End of Klasse1 class body
 ************************************************************/
