// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define tes_Klasse2_BODY

/************************************************************
 Klasse2 class body
 ************************************************************/

// include associated header file
#include "tes/Klasse2.h"

// Derived includes directives

namespace tes {

// static attributes (if any)

/**
 * 
 * @param name 
 */
void Klasse2::setName(std::string /*in*/name) {
	Name = name;
}

/**
 * 
 * @return name 
 */
std::string Klasse2::getName() {
	return Name;
}
//void Klasse2::printName(){}

} // of namespace tes

/************************************************************
 End of Klasse2 class body
 ************************************************************/
