// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef TES_KLASSE1_H
#define TES_KLASSE1_H

/************************************************************
 Klasse1 class header
 ************************************************************/

#include "tes/Pkg_tes.h"

//#include "AnsiCLibrary/Pkg_AnsiCLibrary.h"
#include "tes/Klasse2.h"

namespace tes {

/************************************************************/
/**
 * 
 */
class Klasse1: public Klasse2 {
public:

	/**
	 * 
	 */
	int Variable1;

	/**
	 * 
	 * @return zahl 
	 */
	int getVariable2();

	/**
	 * 
	 * @param zahl 
	 */
	void setVariable2(int /*in*/zahl);

	/**
	 * 
	 * @param Value 
	 */
	Klasse1(int /*in*/Value);

	/**
	 * 
	 */
	~Klasse1();

	/**
	 * 
	 */
	static void Mehtode4();
	/**
	 *
	 */
	void printName();
protected:

	/**
	 * 
	 */
	int Variable3;

	/**
	 * 
	 */
	void Methode3();

private:

	/**
	 * 
	 */
	int Variable2;

	/**
	 * 
	 */
	static int Counter;

	/**
	 * 
	 */
	void Methode2();
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace tes

/************************************************************
 End of Klasse1 class header
 ************************************************************/

#endif
