// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef TES_KLASSE2_H
#define TES_KLASSE2_H

/************************************************************
 Klasse2 class header
 ************************************************************/

#include "tes/Pkg_tes.h"
#include <iostream>
#include "PrimitiveTypes/Pkg_PrimitiveTypes.h"

namespace tes {

/************************************************************/
/**
 * 
 */
class Klasse2 {
public:

	/**
	 * 
	 * @param name 
	 */
	void setName(std::string /*in*/name);

	/**
	 * 
	 * @return name 
	 */
	std::string getName();
	/**
	 *
	 *
	 */
	virtual void printName() = 0;

private:

	/**
	 * 
	 */
	std::string Name;
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace tes

/************************************************************
 End of Klasse2 class header
 ************************************************************/

#endif
