// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef MODEL_AIR_H
#define MODEL_AIR_H

/************************************************************
 Air class header
 ************************************************************/

#include "Model/Pkg_Model.h"

#include "Model/driven.h"
#include "string"

namespace Model {

/************************************************************/
/**
 *
 */
class Air: public driven {
public:
	// virtual void printInfo();
protected:

	/**
	 *
	 * @return isPositionValid
	 */
	std::string checkPosition();

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Model

/************************************************************
 End of Air class header
 ************************************************************/

#endif
