// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define Model_Air_BODY

/************************************************************
 Air class body
 ************************************************************/

// include associated header file
#include "Model/Air.h"

// Derived includes directives

namespace Model {

// static attributes (if any)

/**
 * 
 * @return isPositionValid 
 */
std::string Air::checkPosition() {
}

} // of namespace Model

/************************************************************
 End of Air class body
 ************************************************************/
