// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define Model_buildung_BODY

/************************************************************
 buildung class body
 ************************************************************/

// include associated header file
#include "Model/buildung.h"

// Derived includes directives

namespace Model {

// static attributes (if any)

}// of namespace Model

/************************************************************
 End of buildung class body
 ************************************************************/
