// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define Model_camera_BODY

/************************************************************
 camera class body
 ************************************************************/

// include associated header file
#include "Model/camera.h"

// Derived includes directives

namespace Model {

// static attributes (if any)

/**
 * 
 * @param name 
 * @param type 
 */
camera::camera(std::string /*in*/name, std::string /*in*/type) {
}

/**
 * 
 */
void camera::printInfo() {
}

} // of namespace Model

/************************************************************
 End of camera class body
 ************************************************************/
