// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef MODEL_CAMERA_H
#define MODEL_CAMERA_H

/************************************************************
 camera class header
 ************************************************************/

#include "Model/Pkg_Model.h"

#include "Model/sensor.h"
#include "string"

namespace Model {

/************************************************************/
/**
 * 
 */
class camera: public sensor {
public:

	/**
	 * 
	 * @param name 
	 * @param type 
	 */
	camera(std::string /*in*/name, std::string /*in*/type);

	/**
	 * 
	 */
	void printInfo();

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Model

/************************************************************
 End of camera class header
 ************************************************************/

#endif
