// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define Model_canonn_BODY

/************************************************************
 canonn class body
 ************************************************************/

// include associated header file
#include "Model/cannon.h"

// Derived includes directives

namespace Model {

// static attributes (if any)

/**
 *
 * @param name
 * @param type
 * @param Caliber
 */
cannon::cannon(std::string /*in*/name, std::string /*in*/type,
		float /*in*/c)   {
			Caliber = c;
			weapon::setName(name);
			weapon::setType(type);
}

/**
 *
 * @return
 */
float cannon::getCaliber() {
	return Caliber;
}

/**
 *
 * @param caliber
 */
void cannon::setCaliber(float /*in*/c) {
	Caliber = c;
}

/**
 *
 * @param munition
 */
void cannon::setMunition(Munition* /*in*/m) {
	munitionList.push_back(m);
}

/**
 *
 * @return munition
 */
// Munition cannon::getMunition() {
// }

/**
 *
 */
void cannon::printInfo() {
	std::cout<<"Name:"<< weapon::getName()<<" Type:"<<weapon::getType()<<" Caliber:" <<Caliber<<std::endl;

}

} // of namespace Model

/************************************************************
 End of canonn class body
 ************************************************************/
