// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef MODEL_CANONN_H
#define MODEL_CANONN_H

/************************************************************
 canonn class header
 ************************************************************/

#include "Model/Pkg_Model.h"

#include "AnsiCLibrary/Pkg_AnsiCLibrary.h"
#include "EcorePrimitiveTypes/Pkg_EcorePrimitiveTypes.h"
#include "Model/Munition.h"
#include "Model/weapon.h"
#include "string"
#include <list>

namespace Model {

/************************************************************/
/**
 *
 */
class cannon: public weapon {
public:

	/**
	 *
	 * @param name
	 * @param type
	 * @param Caliber
	 */
	cannon(std::string /*in*/name, float /*in*/c);

	/**
	 *
	 * @return
	 */
	float getCaliber();

	/**
	 *
	 * @param caliber
	 */
	void setCaliber(float /*in*/c);

	/**
	 *
	 * @param munition
	 */
	void setMunition(Munition* /*in*/m);

	/**
	 *
	 * @return munition
	 */
	// Munition getMunition();

	/**
	 *
	 */
	void printInfo();

private:
	/**
	 *
	 */
	float Caliber;
	/**
	 *
	 */
	 std::list<Munition*> munitionList;
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Model

/************************************************************
 End of canonn class header
 ************************************************************/

#endif
