// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define Model_civalShip_BODY

/************************************************************
 civalShip class body
 ************************************************************/

// include associated header file
#include "Model/civalShip.h"

// Derived includes directives
#include "Model/sensor.h"

namespace Model {

// static attributes (if any)

/**
 *
 * @param sensor
 */
void civalShip::addSensor(sensor /*in*/sensor) {
}

/**
 *
 */
void civalShip::rmSensor() {
}

/**
 *
 * @param Name
 * @param Typ
 */
civalShip::civilShip(std::string /*in*/Name, std::string /*in*/Typ) {
}

/**
 *
 * @return sensors
 */
sensor civalShip::getSensors() {
}

} // of namespace Model
void civilShip::printInfo(){
  std::cout << "hello world" << '\n';

}


/************************************************************
 End of civalShip class body
 ************************************************************/
