// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define Model_civilShip_BODY

/************************************************************
 civilShip class body
 ************************************************************/

// include associated header file
#include "Model/civilShip.h"

// Derived includes directives
#include "Model/sensor.h"

namespace Model {

// static attributes (if any)
/**
 *
 * @param Name
 * @param Typ
 */
civilShip::civilShip(std::string /*in*/n, std::string /*in*/t) {
  object::setName(n);
	driven::setType(t);
	object::setKind("Platform");
  object::incrementCounter();
  equipment = NULL;
  driven::setEquipment(NULL);

}

civilShip::~civilShip(){
  object::decrementCounter();
  if (object::getMembership() =="Friendly") {
    object::decrementCounterFriendly();
  } else if(object::getMembership() =="Enemy"){
    object::decrementCounterEnemy();
  }else if (object::getMembership() =="Neutral"){
    object::decrementCounterNeutral();
  }
}
/**
 *
 * @param sensor
 */
void civilShip::addSensor(sensor /*in*/*s) {
  sensorList.push_back(s);
  if (equipment == NULL) {
    equipment = new Model::Equipment("Alpha");
    equipment->addSensor(s);

  } else {
    equipment->addSensor(s);
  }
  driven::setEquipment(equipment);


}

/**
 *
 */
void civilShip::rmSensor() {
  sensorList.clear();
  equipment = NULL;
  driven::setEquipment(NULL);


}



/**
 *
 * @return sensors
 */
std::list<sensor*> civilShip::getSensors() {
  if (equipment == NULL) {
    return sensorList;

  } else {
  return  equipment->getSensor();
  }

}

void civilShip::printInfo(){
  std::cout << "Name:" << object::getName() <<" "<< "Typ:" << driven::getType() <<" "<< object::getMembership()<<'\n';
  equipment->printInfo();

}
} // of namespace Model


/************************************************************
 End of civilShip class body
 ************************************************************/
