// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define Model_civilShip_BODY

/************************************************************
 civilShip class body
 ************************************************************/

// include associated header file
#include "Model/civilShip.h"

// Derived includes directives
#include "Model/sensor.h"

namespace Model {

// static attributes (if any)
/**
 *
 * @param Name
 * @param Typ
 */
civilShip::civilShip(std::string /*in*/n, std::string /*in*/t) {
  object::setName(n);
	driven::setType(t);
	object::setKind("Platform");
}
/**
 *
 * @param sensor
 */
void civilShip::addSensor(sensor /*in*/*s) {
  sensorList.push_back(s);

}

/**
 *
 */
void civilShip::rmSensor() {
  sensorList.clear();

}



/**
 *
 * @return sensors
 */
std::list<sensor*> civilShip::getSensors() {
  return sensorList;

}

void civilShip::printInfo(){
  std::cout << "Name:" << object::getName() <<" "<< "Typ:" << driven::getType() <<'\n';

}
} // of namespace Model


/************************************************************
 End of civilShip class body
 ************************************************************/
