// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define Model_civilPlane_BODY

/************************************************************
 civilPlane class body
 ************************************************************/

// include associated header file
#include "Model/civilPlane.h"

// Derived includes directives
#include "Model/sensor.h"

namespace Model {

// static attributes (if any)

/**
 *
 */
void civilPlane::rmSensor() {
  sensorList.clear();
}

/**
 *
 * @param sensor
 */
void civilPlane::addSensor(sensor /*in*/*s) {
  sensorList.push_back(s);

}

/**
 *
 * @param Name
 * @param Typ
 */
civilPlane::civilPlane(std::string /*in*/n, std::string /*in*/t) {
object::setName(n);
driven::setType(t);
object::setKind("Platform");
}

/**
 *
 * @return sensors
 */
std::list<sensor*> civilPlane::getSensors() {
  return sensorList;
}
void civilPlane::printInfo(){
	  std::cout << "Name:" << object::getName() <<" "<< "Typ:" << driven::getType() <<'\n';

}
} // of namespace Model

/************************************************************
 End of civilPlane class body
 ************************************************************/
