// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define Model_civilPlane_BODY

/************************************************************
 civilPlane class body
 ************************************************************/

// include associated header file
#include "Model/civilPlane.h"

// Derived includes directives
#include "Model/sensor.h"

namespace Model {

// static attributes (if any)

/**
 * 
 */
void civilPlane::rmSensor() {
}

/**
 * 
 * @param sensor 
 */
void civilPlane::addSensor(sensor /*in*/sensor) {
}

/**
 * 
 * @param Name 
 * @param Typ 
 */
civilPlane::civilPlane(std::string /*in*/Name, std::string /*in*/Typ) {
}

/**
 * 
 * @return sensors 
 */
sensor civilPlane::getSensors() {
}

} // of namespace Model

/************************************************************
 End of civilPlane class body
 ************************************************************/
