// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef MODEL_CIVILPLANE_H
#define MODEL_CIVILPLANE_H

/************************************************************
 civilPlane class header
 ************************************************************/

#include "Model/Pkg_Model.h"

#include "Model/Air.h"
#include "string"
#include <list>

namespace Model {
class sensor;
}

namespace Model {

/************************************************************/
/**
 *
 */
class civilPlane: public Air {
public:
	/**
	 *
	 * @param Name
	 * @param Typ
	 */
	civilPlane(std::string /*in*/n, std::string /*in*/t);

	/**
	 *
	 */
	void rmSensor();

	/**
	 *
	 * @param sensor
	 */
	void addSensor(sensor /*in*/*s);



	/**
	 *
	 * @return sensors
	 */
	std::list<sensor*> getSensors();
	/*
	 *
	 *
	 */
	 void printInfo();
private:
	/**
	 *
	 */
	 std::list<sensor*> sensorList;
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Model

/************************************************************
 End of civilPlane class header
 ************************************************************/

#endif
