// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define Model_driven_BODY

/************************************************************
 driven class body
 ************************************************************/

// include associated header file
#include "Model/driven.h"

// Derived includes directives

namespace Model {

// static attributes (if any)

/**
 *
 * @return
 */
std::string driven::getCategory() {
return Category;
}

/**
 *
 * @param name
 */
void driven::setCategory(std::string /*in*/name) {
Category = name;
}

/**
 *
 */
void driven::rmAllEquipment() {
}

/**
 *
 * @param velocity
 */
void driven::setVelo(Vector3D /*in*/v) {
Velocity.x = v.x;
Velocity.y = v.y;
Velocity.z = v.z;
}

/**
 *
 * @return velocity
 */
Vector3D driven::getVelo() {
return Velocity;
}

/**
 *
 * @param orientation
 */
void driven::setOrientation(Vector3D /*in*/o) {
Orientation.x = o.x;
Orientation.y = o.y;
Orientation.z = o.z;
}

/**
 *
 * @return orientation
 */
Vector3D driven::getOrientation() {
  return Orientation;
}

/**
 *
 * @return
 */
// std::string driven::getSubCategory() {
// }
//
// /**
//  *
//  * @param name
//  */
// void driven::setSubCategory(std::string /*in*/name) {
//
// }

/**
 *
 * @param type
 */
void driven::setType(std::string /*in*/type) {
  Type = type;
}

/**
 *
 * @return type
 */
std::string driven::getType() {
  return Type;
}

void driven::printInfo(){

}

 void driven::creatDIS_PDU() {
   //entity Type
   // std::string ki = driven::getkind();
   enum kindValue {
     Other = 0,
     Platform = 1,
     Munition = 2,
     Life_form = 3,
     Environmental = 4,
     Cultural_feature = 5,
     Supply = 6,
     Radio = 7,
     Expendalbe = 8,
     Sensor_Emmiter = 9
     };

     

   // std::string cat = driven::getCategory();
   // std::string count = driven::getCountry();
   // std::string dom = driven::getDomain();
   // std::string typ = driven::getType();

 }

} // of namespace Model

/************************************************************
 End of driven class body
 ************************************************************/
