// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define Model_Land_BODY

/************************************************************
 Land class body
 ************************************************************/

// include associated header file
#include "Model/Land.h"

// Derived includes directives

namespace Model {

// static attributes (if any)

/**
 * 
 * @return isPositionValid 
 */
std::string Land::checkPosition() {
}

} // of namespace Model

/************************************************************
 End of Land class body
 ************************************************************/
