// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define Model_military_BODY

/************************************************************
 military class body
 ************************************************************/

// include associated header file
#include "Model/military.h"

// Derived includes directives
#include "Model/Equipment.h"

namespace Model {

// static attributes (if any)

/**
 *
 */
void military::calcShoot() {
}

/**
 *
 * @param Name
 */
void military::addEquipment(Equipment /*in*/*eq) {
  equipment = eq;
  driven::setEquipment(eq);
}

/**
 *
 */
void military::rmEquipment() {
  equipment = NULL;

}

/**
 *
 * @param Name
 * @param Type
 */
military::military(std::string /*in*/Name, std::string /*in*/Type,std::string /*in*/country) {
  object::setName(Name);
  driven::setType(Type);
  object::setCountry(country);
  object::setKind("Platform");
  object::SetDomain("Land");
  object::setPosition(0,0,0);

}

/**
 *
 * @return equipment
 */
Equipment* military::getEquipment() {
  return equipment;
}
void military::printInfo(){
  std::cout << "Name:" << object::getName() <<" "<< "Typ:" << driven::getType() <<'\n';

  equipment->printInfo();

}
} // of namespace Model

/************************************************************
 End of military class body
 ************************************************************/
