// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define Model_military_BODY

/************************************************************
 military class body
 ************************************************************/

// include associated header file
#include "Model/military.h"

// Derived includes directives
#include "Model/Equipment.h"

namespace Model {

// static attributes (if any)

/**
 * 
 */
void military::calcShoot() {
}

/**
 * 
 * @param Name 
 */
void military::addEquipment(Equipment /*in*/Name) {
}

/**
 * 
 */
void military::rmEquipment() {
}

/**
 * 
 * @param Name 
 * @param Type 
 */
military::military(std::string /*in*/Name, std::string /*in*/Type) {
}

/**
 * 
 * @return equipment 
 */
Equipment military::getEquipment() {
}

} // of namespace Model

/************************************************************
 End of military class body
 ************************************************************/
