// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef MODEL_MOVABLE_H
#define MODEL_MOVABLE_H

/************************************************************
 movable class header
 ************************************************************/

#include "Model/Pkg_Model.h"

#include "Model/nonDriven.h"

namespace Model {

/************************************************************/
/**
 * 
 */
class movable: public nonDriven {

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Model

/************************************************************
 End of movable class header
 ************************************************************/

#endif
