// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef MODEL_MUNITION_H
#define MODEL_MUNITION_H

/************************************************************
 Munition class header
 ************************************************************/

#include "Model/Pkg_Model.h"

#include "AnsiCLibrary/Pkg_AnsiCLibrary.h"
#include "string"

namespace Model {

/************************************************************/
/**
 * 
 */
class Munition {
public:

	/**
	 * 
	 * @param value 
	 */
	void setType(std::string /*in*/value);

	/**
	 * 
	 * @return value 
	 */
	std::string getkind();

	/**
	 * 
	 * @return value 
	 */
	std::string getFuse();

	/**
	 * 
	 * @param value 
	 */
	void setFuse(std::string /*in*/value);

private:
	/**
	 * 
	 */
	int Kind;
	/**
	 * 
	 */
	std::string fuse;
	/**
	 * 
	 */
	std::string typ;
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Model

/************************************************************
 End of Munition class header
 ************************************************************/

#endif
