// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define Model_Munition_BODY

/************************************************************
 Munition class body
 ************************************************************/

// include associated header file
#include "Model/Munition.h"

// Derived includes directives

namespace Model {

// static attributes (if any)

/**
 *
 * @param type
 */
void Munition::setType(std::string /*in*/t) {
  Typ = t;

}
/**
 *
 * @param kind
 */
 void Munition::setkind(int /*in*/ k){

   Kind = k;
 }
/**
 *
 * @return kind
 */
int Munition::getkind() {
  return Kind;
}

/**
 *
 * @return fuse
 */
std::string Munition::getFuse() {
  return Fuse;
}

/**
 *
 * @param fuse
 */
void Munition::setFuse(std::string /*in*/f) {
  Fuse = f;

}

} // of namespace Model

/************************************************************
 End of Munition class body
 ************************************************************/
