// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define Model_Munition_BODY

/************************************************************
 Munition class body
 ************************************************************/

// include associated header file
#include "Model/Munition.h"

// Derived includes directives

namespace Model {

// static attributes (if any)

/**
 * 
 * @param value 
 */
void Munition::setType(std::string /*in*/value) {
}

/**
 * 
 * @return value 
 */
std::string Munition::getkind() {
}

/**
 * 
 * @return value 
 */
std::string Munition::getFuse() {
}

/**
 * 
 * @param value 
 */
void Munition::setFuse(std::string /*in*/value) {
}

} // of namespace Model

/************************************************************
 End of Munition class body
 ************************************************************/
