// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef MODEL_MUNITION_H
#define MODEL_MUNITION_H

/************************************************************
 Munition class header
 ************************************************************/

#include "Model/Pkg_Model.h"

#include "AnsiCLibrary/Pkg_AnsiCLibrary.h"
#include "string"

namespace Model {

/************************************************************/
/**
 *
 */
class Munition {
public:

	/**
	 *
	 * @param type
	 */
	void setType(std::string /*in*/t);
	/**
	 *
	 * @param kind
	 */
	void setkind(int /*in*/ k);
	/**
	 *
	 * @return kind
	 */
	int getkind();

	/**
	 *
	 * @return fuse
	 */
	std::string getFuse();

	/**
	 *
	 * @param fuse
	 */
	void setFuse(std::string /*in*/f);



private:
	/**
	 *
	 */
	int Kind;
	/**
	 *
	 */
	std::string Fuse;
	/**
	 *
	 */
	std::string Typ;
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Model

/************************************************************
 End of Munition class header
 ************************************************************/

#endif
