// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define Model_nonDriven_BODY

/************************************************************
 nonDriven class body
 ************************************************************/

// include associated header file
#include "Model/nonDriven.h"

// Derived includes directives

namespace Model {

// static attributes (if any)

}// of namespace Model

/************************************************************
 End of nonDriven class body
 ************************************************************/
