// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define Model_radar_BODY

/************************************************************
 radar class body
 ************************************************************/

// include associated header file
#include "Model/radar.h"

// Derived includes directives

namespace Model {

// static attributes (if any)

/**
 * 
 * @param type 
 * @param range 
 * @param name 
 */
radar::radar(std::string /*in*/type, float /*in*/range,
		std::string /*in*/name) {
}

/**
 * 
 */
void radar::printInfo() {
}

/**
 * 
 * @param Name 
 */
void radar::setRange(std::string /*in*/Name) {
}

/**
 * 
 * @return type 
 */
std::string radar::getRange() {
}

} // of namespace Model

/************************************************************
 End of radar class body
 ************************************************************/
