// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef MODEL_ROCKET_H
#define MODEL_ROCKET_H

/************************************************************
 rocket class header
 ************************************************************/

#include "Model/Pkg_Model.h"

#include "AnsiCLibrary/Pkg_AnsiCLibrary.h"
#include "Model/Munition.h"
#include "Model/weapon.h"
#include "string"

namespace Model {

/************************************************************/
/**
 *
 */
class rocket: public Munition, public weapon {
public:

	/**
	 *
	 * @param t
	 */
	rocket(std::string /*in*/n,	std::string /*in*/t, int /*in*/r);

	/**
	 *
	 */
	void printInfo();

	


private:
	/**
	 *
	 */
	int Range;
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Model

/************************************************************
 End of rocket class header
 ************************************************************/

#endif
