// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define Model_rocket_BODY

/************************************************************
 rocket class body
 ************************************************************/

// include associated header file
#include "Model/rocket.h"

// Derived includes directives

namespace Model {

// static attributes (if any)

/**
 *
 * @param t
 */
rocket::rocket(std::string /*in*/n,	std::string /*in*/t, int /*in*/r) : Range(r) {
  weapon::setName(n);
	weapon::setType(t);
}

/**
 *
 */
void rocket::printInfo() {
  std::cout<< "Name:"<<weapon::getName() << " Type:"<<weapon::getType() << " Range:" << Range<<std::endl;

}



} // of namespace Model

/************************************************************
 End of rocket class body
 ************************************************************/
