// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef MODEL_ROCKET_H
#define MODEL_ROCKET_H

/************************************************************
 rocket class header
 ************************************************************/

#include "Model/Pkg_Model.h"

#include "AnsiCLibrary/Pkg_AnsiCLibrary.h"
#include "Model/Munition.h"
#include "Model/weapon.h"
#include "string"

namespace Model {

/************************************************************/
/**
 * 
 */
class rocket: public Munition, public weapon {
public:

	/**
	 * 
	 * @param t 
	 */
	rocket(std::string /*in*/t);

	/**
	 * 
	 */
	void printInfo();

	/**
	 * 
	 * @param Name 
	 */
	void setType(std::string /*in*/Name);

	/**
	 * 
	 * @param type 
	 */
	void getType(std::string /*in*/type);

private:
	/**
	 * 
	 */
	int range;
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Model

/************************************************************
 End of rocket class header
 ************************************************************/

#endif
