// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define Model_rocket_BODY

/************************************************************
 rocket class body
 ************************************************************/

// include associated header file
#include "Model/rocket.h"

// Derived includes directives

namespace Model {

// static attributes (if any)

/**
 * 
 * @param t 
 */
rocket::rocket(std::string /*in*/t) {
}

/**
 * 
 */
void rocket::printInfo() {
}

/**
 * 
 * @param Name 
 */
void rocket::setType(std::string /*in*/Name) {
}

/**
 * 
 * @param type 
 */
void rocket::getType(std::string /*in*/type) {
}

} // of namespace Model

/************************************************************
 End of rocket class body
 ************************************************************/
