// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define Model_sensor_BODY

/************************************************************
 sensor class body
 ************************************************************/

// include associated header file
#include "Model/sensor.h"

// Derived includes directives

namespace Model {

// static attributes (if any)

/**
 * 
 * @param n 
 */
void sensor::setName(std::string /*in*/n) {
}

/**
 * 
 * @return name 
 */
std::string sensor::getName() {
}

/**
 * 
 * @param name 
 */
void sensor::setCategory(std::string /*in*/name) {
}

/**
 * 
 * @return  
 */
std::string sensor::getCategory() {
}

/**
 * 
 * @return type 
 */
std::string sensor::getType() {
}

/**
 * 
 * @param Name 
 */
void sensor::setType(std::string /*in*/Name) {
}

} // of namespace Model

/************************************************************
 End of sensor class body
 ************************************************************/
