// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define Model_sonar_BODY

/************************************************************
 sonar class body
 ************************************************************/

// include associated header file
#include "Model/sonar.h"

// Derived includes directives

namespace Model {

// static attributes (if any)

/**
 * 
 * @param name 
 * @param type 
 */
sonar::sonar(std::string /*in*/name, std::string /*in*/type) {
}

/**
 * 
 */
void sonar::printInfo() {
}

} // of namespace Model

/************************************************************
 End of sonar class body
 ************************************************************/
