// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef MODEL_SURFACE_H
#define MODEL_SURFACE_H

/************************************************************
 Surface class header
 ************************************************************/

#include "Model/Pkg_Model.h"

#include "Model/driven.h"
#include "string"

namespace Model {

/************************************************************/
/**
 *
 */
class Surface: public driven {

public:

	virtual void printInfo();
protected:

	/**
	 *
	 * @return isPositionValid
	 */
	void checkPosition();


};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Model

/************************************************************
 End of Surface class header
 ************************************************************/

#endif
