// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef MODEL_VLS_H
#define MODEL_VLS_H

/************************************************************
 vls class header
 ************************************************************/

#include "Model/Pkg_Model.h"

#include "AnsiCLibrary/Pkg_AnsiCLibrary.h"
#include "Model/rocket.h"
#include "Model/weapon.h"
#include "string"

namespace Model {

/************************************************************/
/**
 *
 */
class vls: public weapon {
public:

	/**
	 *
	 * @param name n
	 * @param cells
	 * @param type t
	 */
	vls(std::string /*in*/n, std::string /*in*/t, int /*in*/number);

	/**
	 *
	 */
	void printInfo();

	/**
	 *
	 * @param rocket
	 */
	void addRocket(rocket /*in*/*r);

	/**
	 *
	 * @param
	 */
	void rmRocket(rocket /*in*/null);

	/**
	 *
	 * @param n
	 */
	void setNumberOfCells(int /*in*/n);

	/**
	 *
	 */
	void getNumberOfCells();

private:
	/**
	 *
	 */
	 std::list<rocket*> rocketList;
	/**
	 *
	 */
	int numberOfCells;
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Model

/************************************************************
 End of vls class header
 ************************************************************/

#endif
