// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define Model_vls_BODY

/************************************************************
 vls class body
 ************************************************************/

// include associated header file
#include "Model/vls.h"

// Derived includes directives

namespace Model {

// static attributes (if any)

/**
 * 
 * @param name 
 * @param cells 
 * @param type 
 */
vls::vls(std::string /*in*/name, std::string /*in*/cells,
		std::string /*in*/type) {
}

/**
 * 
 */
void vls::printInfo() {
}

/**
 * 
 * @param type 
 */
void vls::getType(std::string /*in*/type) {
}

/**
 * 
 * @param Name 
 */
void vls::setType(std::string /*in*/Name) {
}

/**
 * 
 * @param rocket 
 */
void vls::addRocket(rocket /*in*/rocket) {
}

/**
 * 
 * @param  
 */
void vls::rmRocket(rocket /*in*/null) {
}

/**
 * 
 * @param n 
 */
void vls::setNumberOfCells(int /*in*/n) {
}

/**
 * 
 */
void vls::getNumberOfCells() {
}

} // of namespace Model

/************************************************************
 End of vls class body
 ************************************************************/
