// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef MODEL_VLS_H
#define MODEL_VLS_H

/************************************************************
 vls class header
 ************************************************************/

#include "Model/Pkg_Model.h"

#include "AnsiCLibrary/Pkg_AnsiCLibrary.h"
#include "Model/rocket.h"
#include "Model/weapon.h"
#include "string"

namespace Model {

/************************************************************/
/**
 * 
 */
class vls: public weapon {
public:

	/**
	 * 
	 * @param name 
	 * @param cells 
	 * @param type 
	 */
	vls(std::string /*in*/name, std::string /*in*/cells,
			std::string /*in*/type);

	/**
	 * 
	 */
	void printInfo();

	/**
	 * 
	 * @param type 
	 */
	void getType(std::string /*in*/type);

	/**
	 * 
	 * @param Name 
	 */
	void setType(std::string /*in*/Name);

	/**
	 * 
	 * @param rocket 
	 */
	void addRocket(rocket /*in*/rocket);

	/**
	 * 
	 * @param  
	 */
	void rmRocket(rocket /*in*/null);

	/**
	 * 
	 * @param n 
	 */
	void setNumberOfCells(int /*in*/n);

	/**
	 * 
	 */
	void getNumberOfCells();

private:
	/**
	 * 
	 */
	rocket rockets[];
	/**
	 * 
	 */
	int numberOfCells;
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Model

/************************************************************
 End of vls class header
 ************************************************************/

#endif
