// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define Model_warPlane_BODY

/************************************************************
 warPlane class body
 ************************************************************/

// include associated header file
#include "Model/warPlane.h"

// Derived includes directives
#include "Model/Equipment.h"

namespace Model {

// static attributes (if any)

/**
 * 
 * @param Name 
 * @param Type 
 */
warPlane::warPlane(std::string /*in*/Name, std::string /*in*/Type) {
}

/**
 * 
 */
void warPlane::rmEquipment() {
}

/**
 * 
 * @param Name 
 */
void warPlane::addEquipment(Equipment /*in*/Name) {
}

/**
 * 
 */
void warPlane::calcShoot() {
}

/**
 * 
 * @return equipment 
 */
Equipment warPlane::getEquipment() {
}

} // of namespace Model

/************************************************************
 End of warPlane class body
 ************************************************************/
