// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define Model_weapon_BODY

/************************************************************
 weapon class body
 ************************************************************/

// include associated header file
#include "Model/weapon.h"

// Derived includes directives

namespace Model {

// static attributes (if any)

/**
 *
 * @param n
 */
void weapon::setName(std::string /*in*/n) {
  Name = n;
}

/**
 *
 * @return name
 */
std::string weapon::getName() {
  return Name;
}


void weapon::setType(std::string t){
Type = t;
}


std::string weapon::getType() {
return Type;
}

void weapon::printInfo(){

}

void weapon::setGunValues(double orientation, double elevation){
GunValues.Orientation = orientation;
GunValues.Elevation = elevation;
}

gunValues weapon::getGunValues(){

  return GunValues;
}

void weapon::moveGuns(double orientationrate, double elevationrate, double dt){
GunValues.Orientation = GunValues.Orientation +orientationrate * dt;
GunValues.Elevation = GunValues.Elevation +elevationrate * dt;


}


} // of namespace Model

/************************************************************
 End of weapon class body
 ************************************************************/
