// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef MODEL_WEAPON_H
#define MODEL_WEAPON_H

/************************************************************
 weapon class header
 ************************************************************/

#include "Model/Pkg_Model.h"

#include "string"

namespace Model {

/************************************************************/
/**
 *
 */
class weapon {
public:

	/**
	 *
	 * @param n
	 */
	void setName(std::string /*in*/n);

	/**
	 *
	 * @return name
	 */
	std::string getName();
	/**
	 *
	 * @param t
	 */
	void setType(std::string t);
	/**
	 *
	 * @return type
	 */
	std::string getType();

	/**
	 *
	 */
	virtual void printInfo();

private:
	/**
	 *
	 */
	std::string Name;
	/**
	 *
	 */
	std::string Type;
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Model

/************************************************************
 End of weapon class header
 ************************************************************/

#endif
