// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef MODEL_BUILDUNG_H
#define MODEL_BUILDUNG_H

/************************************************************
 buildung class header
 ************************************************************/

#include "Model/Pkg_Model.h"

#include "Model/nonDriven.h"

namespace Model {

/************************************************************/
/**
 * 
 */
class buildung: public nonDriven {

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Model

/************************************************************
 End of buildung class header
 ************************************************************/

#endif
