// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define Model_civil_BODY

/************************************************************
 civil class body
 ************************************************************/

// include associated header file
#include "Model/civil.h"

// Derived includes directives

namespace Model {

// static attributes (if any)

}// of namespace Model

/************************************************************
 End of civil class body
 ************************************************************/
