// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef MODEL_CIVIL_H
#define MODEL_CIVIL_H

/************************************************************
 civil class header
 ************************************************************/

#include "Model/Pkg_Model.h"

#include "Model/Land.h"

namespace Model {

/************************************************************/
/**
 *
 */
class civil: public Land {
public:

  void printInfo();
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Model

/************************************************************
 End of civil class header
 ************************************************************/

#endif
