// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef DIS_ENUM_H
#define DIS_ENUM_H

/************************************************************
 driven class header
 ************************************************************/

#include "Model/Pkg_Model.h"

#include "AnsiCLibrary/Pkg_AnsiCLibrary.h"
#include "object.h"
#include "string"
#include <map>
//

namespace Model {

/************************************************************/
/**
 *
 */
class DIS_enum {


public:
  DIS_enum();
  // ~DIS_enum();

  DIS_EntityType_Variables getDISEntityType(std::string kind, std::string domain, std::string country, std::string category,  std::string subcategory,  std::string specific,  std::string extra);

   int getDISDomain(std::string domain);

   //std::string checkContentType(std::string /*in*/ content);

private:
  std::map<int,std::string> Kind;
  std::map<int,std::string> DomainPlatform;
  std::map<int,std::string> DomainMunition;
  std::map<int,std::string> Country;
  std::map<int,std::string> CategoryLand;
  std::map<int,std::string> CategoryAir;
  std::map<int,std::string> CategorySurface;
  std::map<int,std::string> CategorySubSurface;
  std::map<int,std::string> CategorySpace;
  std::map<int,std::string> CategoryMunition;

  std::map<int,std::string> GermanLandTankSubcategory;
  std::map<int,std::string> GermanGuidedMissileFrigate;

  std::map<int,std::string> USLandTankSubcategory;
  std::map<int,std::string> USCarrier;
  std::map<int,std::string> USGuidedMissileCrusier;
  std::map<int,std::string> USGuidedMissileDestroyer;
  std::map<int,std::string> USDestroyer;
  std::map<int,std::string> USGuidedMissileFrigate;


  std::map<int,std::string> RussiaLandTankSubcategory;
  std::map<int,std::string> RussiaCarrier;
  std::map<int,std::string> RussiaGuidedMissileCrusier;
  std::map<int,std::string> RussiaGuidedMissileDestroyer;
  std::map<int,std::string> RussiaDestroyer;
  std::map<int,std::string> RussiaGuidedMissileFrigate;


  //std::map<char,QString> specific;
  //std::map<char,QString> extra;


};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Model

/************************************************************
 End of driven class header
 ************************************************************/

#endif
