// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define Model_movable_BODY

/************************************************************
 movable class body
 ************************************************************/

// include associated header file
#include "Model/movable.h"

// Derived includes directives

namespace Model {

// static attributes (if any)

}// of namespace Model

/************************************************************
 End of movable class body
 ************************************************************/
