// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef MODEL_NONDRIVEN_H
#define MODEL_NONDRIVEN_H

/************************************************************
 nonDriven class header
 ************************************************************/

#include "Model/Pkg_Model.h"

#include "Model/object.h"

namespace Model {

/************************************************************/
/**
 * 
 */
class nonDriven: public object {

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Model

/************************************************************
 End of nonDriven class header
 ************************************************************/

#endif
