// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define Model_sonar_BODY

/************************************************************
 sonar class body
 ************************************************************/

// include associated header file
#include "Model/sonar.h"

// Derived includes directives

namespace Model {

// static attributes (if any)

/**
 *
 * @param name
 * @param type
 */
sonar::sonar(std::string /*in*/n) {
  sensor::setName(n);
	sensor::setType("SONAR");
}

/**
 *
 */
void sonar::printInfo() {
  std::cout<< "Name:"<< sensor::getName()<<" Type:"<< sensor::getType()<< std::endl;

}

} // of namespace Model

/************************************************************
 End of sonar class body
 ************************************************************/
