// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define Model_Subsurface_BODY

/************************************************************
 Subsurface class body
 ************************************************************/

// include associated header file
#include "Model/Subsurface.h"

// Derived includes directives

namespace Model {

// static attributes (if any)

/**
 * 
 * @return isPositionValid 
 */
std::string Subsurface::checkPosition() {
}

} // of namespace Model

/************************************************************
 End of Subsurface class body
 ************************************************************/
