// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define Model_Surface_BODY

/************************************************************
 Surface class body
 ************************************************************/

// include associated header file
#include "Model/Surface.h"

// Derived includes directives

namespace Model {

// static attributes (if any)

/**
 *
 * @return isPositionValid
 */
void Surface::checkPosition() {
}

void Surface::printInfo(){

}
} // of namespace Model

/************************************************************
 End of Surface class body
 ************************************************************/
